---
title: "NCSSC Database Analyte Graph"
author: "Andrew G. Brown"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: NULL
    template: NULL
    mathjax: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

## NCSSC Database Analyte Graph

Visualization of data in `lab_analyte` table of [Soil Data Access](https://sdmdataaccess.nrcs.usda.gov/)

Using query `"SELECT * from lab_analyte"` and pathString `SDA_lab_analyte/[TYPE]/[SIZE_FRAC_BASE]/[ABBREVIATION]`

```{r, fig.width=20, fig.height=20}
library(soilDB)
library(data.tree)

analytes <- SDA_query("SELECT * from lab_analyte")

res <- lapply(analytes$analyte_abbrev, grepl, analytes$analyte_algorithm)
analyte.sub <- analytes[do.call('c', lapply(res, which)),]
analyte.sub$analyte_size_frac_base[is.na(analyte.sub$analyte_size_frac_base)] <- "NONE"

analyte.sub$pathString <- paste("SDA_lab_analyte", 
                                 analyte.sub$analyte_type, 
                                 analyte.sub$analyte_size_frac_base,
                                 analyte.sub$analyte_abbrev,
                                 sep = "/")
analyte.sub <- as.Node(analyte.sub)

plot(analyte.sub, output="visNetwork")
```
